### ISSUE TITLE
Workshop/Custom Training

### ISSUE THREAD

**Issue by tinyterry97** [ItsBranK/QueueDeck#2]
If possible, can we get QueueDeck to open up the  workshop and custom training menus?

**Comment by ItsBranK** [comment]
There would be no way to automate going into workshop maps with commands that I can think of, you can already use BakkesMod to load into workshop maps yourself if you look into how unreal commands work; but you'll have to do that manually. Plus there's already a command to load into custom training packs called `load_training`.

https://bakkesmod.fandom.com/wiki/Load_training
