### ISSUE TITLE
Play again doesn't work properly

### ISSUE THREAD

**Issue by maciekwiso** [ItsBranK/QueueDeck#3]
I created config file like this:
queue_deselect_playlists
queue_view_ranked
queue_select_rstandard
queue_search_rstandard

But after first game of ranked 3s when I click "Play again" button it doesn't queue again to ranked 3s but to different mode.
I think mode I previously played.

**Comment by ItsBranK** [comment]
`queue_search_rstandard` does everything you typed before that automatically for you, it searches in the ranked standard playlist only. As far s the play again thing that's something I can't fix with the standard BMSDK as it's a problem with Rocket League itself. RLSDK plugins are no longer allowed so I have to only use BMSDK features.
