### ISSUE TITLE
Crashing after update

### ISSUE THREAD

**Issue by emmafaye** [ItsBranK/QueueDeck#4]
After the latest update, all of these commands are causing an instant crash to desktop `queue_search_rstandard`, `queue_search_rdoubles`, `queue_search_rduels`.

**Comment by ItsBranK** [comment]
I can't replicate this issue, are you on the latest version of the plugin?

**Comment by ItsBranK** [comment]
I talked with one of the bm devs, although I can't reproduce this I was told there was an error in their sdk with the bool operator I'm using for null checking MatchmakingWrapper. If I had to guess this could be the reason it's crashing? Nothing I can do if that's the case, will have to wait for the next bm update.

**Comment by emmafaye** [comment]
Yeah, I'm using the latest, and that makes sense. The crashing is also occurring with Instant Suite at the end of the match. I'm going to close this out, thanks!
