### ISSUE TITLE
Queuing extra modes doesn't work properly

### ISSUE THREAD

**Issue by maciekwiso** [ItsBranK/QueueDeck#5]
Using queue commands for extra modes queues to incorrect mode.
Usign command queue_search_esnowday it queues to hoops, queue_search_ehoops queues dropshot and so on.

**Comment by ItsBranK** [comment]
This is a problem with the BakkesModSDK itself not the plugin, I've contacted the devs about the issue so hopefully they will fix it by the next update.

**Comment by ItsBranK** [comment]
Fixed this in the last update, forgot to close issue heh
