### ISSUE TITLE
Feature: graphical interface

### ISSUE THREAD

**Issue by maggaou** [ItsBranK/QueueDeck#7]
Provide a menu to select custom commands using mouse. Similar to
`togglemenu queuemenu`

Other possibly easier implementation: implement fixed commands for ranked/casual 3s, 2s, 1s

**Comment by ItsBranK** [comment]
I have no plans to add any additional features to my plugins anymore, I just pushed an update to bakkesplugins using the latest bmsdk and that appears to have fixed any command issues.
